# Generated by Django 5.2.3 on 2025-06-12 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_book_isbn_alter_author_name_alter_book_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_year']},
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
